name: taxischronodriver
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.0.2
  firebase_database: ^10.0.2
  firebase_core: ^2.1.0
  get: ^4.6.5
  provider: ^6.0.4
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.2.1
  google_sign_in: ^5.4.2
  the_apple_sign_in: ^1.1.1
  cloud_firestore: ^4.0.2  
  google_maps_flutter: ^2.2.1
  geolocator: ^9.0.2
  modal_bottom_sheet: ^2.1.2
  geocoding: ^2.0.5  
  url_launcher: ^6.1.6
  flutter_polyline_points: ^1.0.0
  sliding_up_panel: ^2.0.0+1
  page_transition: ^2.0.9
  intl_phone_number_input: ^0.7.1
  cached_network_image: ^3.2.2
  intl: ^0.17.0
  pinput: ^2.2.16
  flutter_switch: ^0.3.2
  percent_indicator: ^4.2.2
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_rating_bar: ^4.0.1
  firebase_messaging: ^14.2.0
  flutter_local_notifications: ^13.0.0
  dio: ^4.0.6
  flutter_launcher_icons: ^0.11.0
  fluttertoast: ^8.1.2
  flutter_phone_direct_caller: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "images/icone.png"
  
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
