// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZYRrRq7YYTS6BewMAf4KG8e-H-VLwzKg',
    appId: '1:388406613111:web:1f29325671402afc62a272',
    messagingSenderId: '388406613111',
    projectId: 'taxischrono-c12c9',
    authDomain: 'taxischrono-c12c9.firebaseapp.com',
    storageBucket: 'taxischrono-c12c9.appspot.com',
    measurementId: 'G-PVGRBTMHNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVYyZjeyE7UmSJQTSVqkVnYvk_QfGW9sg',
    appId: '1:388406613111:android:3104c566d967dbf662a272',
    messagingSenderId: '388406613111',
    projectId: 'taxischrono-c12c9',
    storageBucket: 'taxischrono-c12c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnJdnwA1d6hT_SO5mPUKt10b6iJbilscw',
    appId: '1:388406613111:ios:85067b9b0c4b61e762a272',
    messagingSenderId: '388406613111',
    projectId: 'taxischrono-c12c9',
    storageBucket: 'taxischrono-c12c9.appspot.com',
    androidClientId: '388406613111-4ama9814rmq80k2ikfg1is3dl8pqd4sa.apps.googleusercontent.com',
    iosClientId: '388406613111-grs0geujeucqj4d4acpqk8k02f9qbvju.apps.googleusercontent.com',
    iosBundleId: 'com.incc.taxischrono.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnJdnwA1d6hT_SO5mPUKt10b6iJbilscw',
    appId: '1:388406613111:ios:85067b9b0c4b61e762a272',
    messagingSenderId: '388406613111',
    projectId: 'taxischrono-c12c9',
    storageBucket: 'taxischrono-c12c9.appspot.com',
    androidClientId: '388406613111-4ama9814rmq80k2ikfg1is3dl8pqd4sa.apps.googleusercontent.com',
    iosClientId: '388406613111-grs0geujeucqj4d4acpqk8k02f9qbvju.apps.googleusercontent.com',
    iosBundleId: 'com.incc.taxischrono.app',
  );
}
